import { Inter } from 'next/font/google'
import './globals.css'
import MovieNav from './navbar.js'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Moview app',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <MovieNav/>
      {children}</body>
    </html>
  )
}
